apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: .dkr.ecr..amazonaws.com/demo-frontend
  newName: .dkr.ecr..amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
