apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: 782638322607.dkr.ecr.ap-northeast-2.amazonaws.com/theci:a1285fb163477012f42008d00a54de8eec877c3e
          ports:
            - containerPort: 80
