apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: primary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: primary
  template:
    metadata:
      labels:
        app: primary
    spec:
      containers:
      - name: primary
        image: apeachcloud/test-home:v0.0
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  labels:
    app: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canary
        image: apeachcloud/test-home:v2.0
        ports:
        - containerPort: 80
