apiVersion: v1
kind: Service
metadata:
  name: primary-service
spec:
  selector:
    app: primary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: canary-service
spec:
  selector:
    app: canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
