apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
images:
- name: 782638322607.dkr.ecr.ap-northeast-2.amazonaws.com/
  newName: 782638322607.dkr.ecr.ap-northeast-2.amazonaws.com/
