apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: 782638322607.dkr.ecr.ap-northeast-2.amazonaws.com/theci:715964e918f79322ed190842b8ecd1f8a004093c
          ports:
            - containerPort: 80
