apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
- name: 782638322607.dkr.ecr.ap-northeast-2.amazonaws.com/theci
  newName: 782638322607.dkr.ecr.ap-northeast-2.amazonaws.com/theci
  newTag: c6ead48eb59ba16881c0cadec1b50546c1912e90
resources:
- ../../resoures
patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
